--- #YAML:1.0
name:               Geo-Coordinates-ETRSTM35FIN
version:            0.01
abstract:           converts Finnish ETRS-TM35FIN coordinate system from/to WGS84 coordinate system
author:
    - Matti Lattu <matti@lattu.biz>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::Exception:  0.27
requires:
    perl:             5.008006
    Test::Exception:  0.27
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
